apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-litellm
  labels: {{- include "wd.labels" . | nindent 4 }}
data:
  config.yaml: |
    model_list:
    {{- range .Values.litellm.models }}
      - model_name: {{ .alias }}
        litellm_params:
          model: {{ .model }}
          api_base: os.environ/OLLAMA_BASE_URL
    {{- end }}
