/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Log */
        get: operations["audit_log_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media_admin_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/{product_id}/{capability}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Media */
        put: operations["set_media_admin_media__product_id___capability__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/{product_id}/{capability}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Media */
        post: operations["reset_media_admin_media__product_id___capability__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/{product_id}/{capability}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Media */
        post: operations["test_media_admin_media__product_id___capability__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_admin_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Model */
        put: operations["set_model_admin_models__alias__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models/{alias}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Model */
        post: operations["reset_model_admin_models__alias__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models/{alias}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model */
        post: operations["test_model_admin_models__alias__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/safeguards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Safeguards */
        get: operations["get_safeguards_admin_safeguards_get"];
        /** Set Safeguards */
        put: operations["set_safeguards_admin_safeguards_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Songs */
        get: operations["list_songs_admin_songs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage Report */
        get: operations["usage_report_admin_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/creations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Creations */
        get: operations["search_creations_creations_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-image-ai/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_products_wd_image_ai_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-image-ai/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_products_wd_image_ai_images__image_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Image
         * @description Delete an image: its files first, then the record.
         */
        delete: operations["delete_image_products_wd_image_ai_images__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-image-ai/images/{image_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description The image as a file the browser saves (browsers ignore `download` on links to the
         *     storage host, ADR-0034).
         */
        get: operations["download_products_wd_image_ai_images__image_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-image-ai/prompt/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance */
        post: operations["enhance_products_wd_image_ai_prompt_enhance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-lipsync-ai/lipsyncs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lipsyncs */
        get: operations["list_lipsyncs_products_wd_lipsync_ai_lipsyncs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-lipsync-ai/lipsyncs/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lipsync */
        get: operations["get_lipsync_products_wd_lipsync_ai_lipsyncs__video_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Lipsync
         * @description Delete a clip (or dismiss a failed one): its files first, then the record. A clip still
         *     being made cannot be deleted: its job is running.
         */
        delete: operations["delete_lipsync_products_wd_lipsync_ai_lipsyncs__video_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-lipsync-ai/lipsyncs/{video_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description The clip as a file the browser saves (browsers ignore `download` on links to the
         *     storage host, ADR-0034).
         */
        get: operations["download_products_wd_lipsync_ai_lipsyncs__video_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-music-ai/prompt/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance */
        post: operations["enhance_products_wd_music_ai_prompt_enhance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-music-ai/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Songs */
        get: operations["list_songs_products_wd_music_ai_songs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-music-ai/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Song */
        get: operations["get_song_products_wd_music_ai_songs__song_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-music-ai/songs/{song_id}/download/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description A file the browser saves. Browsers ignore `download` on links to another origin (the
         *     storage host), so files are served from here with a Content-Disposition. The song is looked
         *     up for this user only, like every other route.
         *
         *     `audio` is the MP3 with the title, lyrics and cover art written into its tag, so a music
         *     player shows the cover. `video` is the cover as a picture with the song playing, made on the
         *     first request and kept in storage.
         */
        get: operations["download_products_wd_music_ai_songs__song_id__download__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-stt-ai/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Languages
         * @description The languages to choose from, and what an upload may be.
         */
        get: operations["languages_products_wd_stt_ai_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-stt-ai/transcripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transcripts */
        get: operations["list_transcripts_products_wd_stt_ai_transcripts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-stt-ai/transcripts/{transcript_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_products_wd_stt_ai_transcripts__transcript_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Transcript
         * @description Delete a transcript (or dismiss a failed one). One still being made cannot be deleted.
         */
        delete: operations["delete_transcript_products_wd_stt_ai_transcripts__transcript_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-stt-ai/transcripts/{transcript_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description The transcript as a file the browser saves: plain text, SRT, WebVTT or JSON.
         */
        get: operations["download_products_wd_stt_ai_transcripts__transcript_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-tts-ai/speeches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Speeches */
        get: operations["list_speeches_products_wd_tts_ai_speeches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-tts-ai/speeches/{speech_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Speech */
        get: operations["get_speech_products_wd_tts_ai_speeches__speech_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Speech
         * @description Delete a result: its file first, then the record.
         */
        delete: operations["delete_speech_products_wd_tts_ai_speeches__speech_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-tts-ai/speeches/{speech_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description The speech as a file the browser saves (browsers ignore `download` on links to the
         *     storage host, ADR-0034).
         */
        get: operations["download_products_wd_tts_ai_speeches__speech_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-tts-ai/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Voices
         * @description The languages and voices the form offers: a gender with no voice is an empty list.
         */
        get: operations["list_voices_products_wd_tts_ai_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-video-ai/prompt/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance */
        post: operations["enhance_products_wd_video_ai_prompt_enhance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-video-ai/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_products_wd_video_ai_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-video-ai/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_products_wd_video_ai_videos__video_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Video
         * @description Delete a clip (or dismiss a failed one): its files first, then the record. A clip still
         *     being made cannot be deleted: its job is running.
         */
        delete: operations["delete_video_products_wd_video_ai_videos__video_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/wd-video-ai/videos/{video_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description The clip as a file the browser saves (browsers ignore `download` on links to the
         *     storage host, ADR-0034).
         */
        get: operations["download_products_wd_video_ai_videos__video_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_products__product_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/uploads/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_products__product_id__uploads_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/uploads/images/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Upload
         * @description Remove the caller's own unused upload (the user took the file back, ADR-0039).
         */
        delete: operations["delete_upload_products__product_id__uploads_images__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/uploads/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Media
         * @description A recording or a video file (ADR-0043): checked by its first bytes, decoded to a clean
         *     16 kHz mono WAV (no video, no tags) in a limited child process, and stored in its place.
         */
        post: operations["upload_media_products__product_id__uploads_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/uploads/media/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Upload
         * @description Remove the caller's own unused upload (the user took the file back, ADR-0039).
         */
        delete: operations["delete_upload_products__product_id__uploads_media__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminSong */
        AdminSong: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Product Id */
            product_id: string;
            /** Title */
            title: string;
            /** User Email */
            user_email: string | null;
            /** User Id */
            user_id: string;
        };
        /** AdminSongPage */
        AdminSongPage: {
            /** Next Before */
            next_before: string | null;
            /** Songs */
            songs: components["schemas"]["AdminSong"][];
        };
        /** AdminUser */
        AdminUser: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /** Email Verified */
            email_verified: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string | null;
            /** Providers */
            providers: string[];
            /** Role */
            role: string;
        };
        /** AdminUserPage */
        AdminUserPage: {
            /** Next Before */
            next_before: string | null;
            /** Users */
            users: components["schemas"]["AdminUser"][];
        };
        /** AuditEntry */
        AuditEntry: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Target Id */
            target_id?: string | null;
            /** Target Type */
            target_type?: string | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Entries */
            entries: components["schemas"]["AuditEntry"][];
        };
        /** BackendView */
        BackendView: {
            /** Description */
            description: string;
            /** Families */
            families: string[];
            /** Fields */
            fields: components["schemas"]["FieldView"][];
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** Binding */
        Binding: {
            /** Api Base */
            api_base?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
        };
        /** DoneEvent */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "done";
            /** Outputs */
            outputs?: {
                [key: string]: unknown;
            };
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Ts */
            ts?: string;
        };
        /** EnhanceIn */
        EnhanceIn: {
            /** Kind */
            kind: string;
            /** Prompt */
            prompt: string;
            /** Upload Id */
            upload_id?: string | null;
        };
        /** EnhanceOut */
        EnhanceOut: {
            /** Changed */
            changed: boolean;
            /** Prompt */
            prompt: string;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** Code */
            code: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "error";
            /**
             * Job Id
             * @default null
             */
            job_id: string | null;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Ts */
            ts?: string;
        };
        /** FieldView */
        FieldView: {
            /** Help */
            help: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Placeholder */
            placeholder: string;
            /** Required */
            required: boolean;
            /** Secret */
            secret: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagePage */
        ImagePage: {
            /** Images */
            images: components["schemas"]["ImageSummary"][];
            /** Next Before */
            next_before: string | null;
        };
        /** ImageSummary */
        ImageSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Image Url */
            image_url: string;
            /** Mode */
            mode: string;
            /** Prompt */
            prompt: string;
            /** Thumb Url */
            thumb_url: string;
            /** Width */
            width: number;
        };
        /** InterruptEvent */
        InterruptEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "interrupt";
            /** Interrupt Id */
            interrupt_id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Ts */
            ts?: string;
        };
        /** JobProgressEvent */
        JobProgressEvent: {
            /** Capability */
            capability: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "job_progress";
            /** Job Id */
            job_id: string;
            /**
             * Preview Url
             * @default null
             */
            preview_url: string | null;
            /**
             * Progress
             * @default null
             */
            progress: number | null;
            /**
             * Queue Position
             * @default null
             */
            queue_position: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Ts */
            ts?: string;
        };
        /** LanguageCatalog */
        LanguageCatalog: {
            /** Languages */
            languages: components["schemas"]["SpokenLanguage"][];
            /**
             * Max Bytes
             * @default 104857600
             */
            max_bytes: number;
            /**
             * Max Seconds
             * @default 1800
             */
            max_seconds: number;
        };
        /** LanguageChoice */
        LanguageChoice: {
            /** English */
            english: string;
            /** Genders */
            genders: {
                [key: string]: components["schemas"]["VoiceChoice"][];
            };
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** LipSyncPage */
        LipSyncPage: {
            /** Lipsyncs */
            lipsyncs: components["schemas"]["LipSyncSummary"][];
            /** Next Before */
            next_before: string | null;
        };
        /** LipSyncSummary */
        LipSyncSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Height */
            height?: number | null;
            /** Id */
            id: string;
            /** Poster Url */
            poster_url?: string | null;
            /** Seconds */
            seconds: number;
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "working" | "done" | "failed";
            /** Style */
            style: string;
            /** Text */
            text: string;
            /** Video Url */
            video_url?: string | null;
            /** Width */
            width?: number | null;
        };
        /** Me */
        Me: {
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
        };
        /** MediaBindingIn */
        MediaBindingIn: {
            /** Api Key */
            api_key?: string | null;
            /** Backend */
            backend: string;
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: string;
            };
        };
        /** MediaList */
        MediaList: {
            /** Backends */
            backends: components["schemas"]["BackendView"][];
            /** Items */
            items: components["schemas"]["MediaView"][];
            /** Secrets Ready */
            secrets_ready: boolean;
        };
        /** MediaTestOutcome */
        MediaTestOutcome: {
            /** Latency Ms */
            latency_ms: number;
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /** MediaUploadResult */
        MediaUploadResult: {
            /** Bytes */
            bytes: number;
            /** Key */
            key: string;
            /** Seconds */
            seconds: number;
            /** Upload Id */
            upload_id: string;
        };
        /** MediaView */
        MediaView: {
            /** Allowed Backends */
            allowed_backends: string[];
            /** Backend */
            backend: string;
            /** Capability */
            capability: string;
            /** Config */
            config: {
                [key: string]: string;
            };
            /** Key Set */
            key_set: boolean;
            /** Product Id */
            product_id: string;
            /** Source */
            source: string;
            /** Updated At */
            updated_at: string | null;
            /** Updated By */
            updated_by: string | null;
            /** Workflow */
            workflow: string | null;
        };
        /** ModelList */
        ModelList: {
            /** Models */
            models: components["schemas"]["ModelView"][];
            /** Providers */
            providers: components["schemas"]["ProviderView"][];
        };
        /** ModelUpdated */
        ModelUpdated: {
            /** Checks */
            checks: string;
            model: components["schemas"]["ModelView"];
        };
        /** ModelView */
        ModelView: {
            /** Alias */
            alias: string;
            /** Api Base */
            api_base: string | null;
            /** Key Set */
            key_set: boolean;
            /** Kind */
            kind: string;
            /** Model */
            model: string | null;
            /** Protected */
            protected: boolean;
            /** Provider */
            provider: string | null;
            /** Purpose */
            purpose: string;
            /** Source */
            source: string;
            /** Updated At */
            updated_at: string | null;
            /** Updated By */
            updated_by: string | null;
        };
        /** NodeEvent */
        NodeEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "node";
            /**
             * Label
             * @default
             */
            label: string;
            /** Node */
            node: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "completed";
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Ts */
            ts?: string;
        };
        /** ProviderView */
        ProviderView: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Model Hint */
            model_hint: string;
            /** Needs Base */
            needs_base: boolean;
            /** Needs Key */
            needs_key: boolean;
        };
        /** ResumeRequest */
        ResumeRequest: {
            /** Interrupt Id */
            interrupt_id?: string | null;
            /** Value */
            value?: unknown;
        };
        /** RunRequest */
        RunRequest: {
            /** Input */
            input?: {
                [key: string]: unknown;
            };
            /** Thread Id */
            thread_id?: string | null;
        };
        /** SafeguardsIn */
        SafeguardsIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** SafeguardsStatus */
        SafeguardsStatus: {
            /** Enabled */
            enabled: boolean;
            /** Forced */
            forced: boolean;
        };
        /** SearchHit */
        SearchHit: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "song" | "image" | "video" | "speech" | "transcript" | "lipsync";
            /**
             * Match
             * @enum {string}
             */
            match: "words" | "meaning";
            /** Product Id */
            product_id: string;
            /** Score */
            score: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Degraded */
            degraded: boolean;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchHit"][];
        };
        /** Segment */
        Segment: {
            /** End */
            end: number;
            /** Start */
            start: number;
            /** Text */
            text: string;
        };
        /** SongDetail */
        SongDetail: {
            /** Audio Url */
            audio_url: string;
            /** Cover Url */
            cover_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Lyrics */
            lyrics: string;
            /** Style */
            style: string;
            /** Title */
            title: string;
        };
        /** SongPage */
        SongPage: {
            /** Next Before */
            next_before: string | null;
            /** Songs */
            songs: components["schemas"]["SongSummary"][];
        };
        /** SongSummary */
        SongSummary: {
            /** Audio Url */
            audio_url: string;
            /** Cover Url */
            cover_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Style */
            style: string;
            /** Title */
            title: string;
        };
        /** SpeechPage */
        SpeechPage: {
            /** Next Before */
            next_before: string | null;
            /** Speeches */
            speeches: components["schemas"]["SpeechSummary"][];
        };
        /** SpeechSummary */
        SpeechSummary: {
            /** Audio Url */
            audio_url: string;
            /** Characters */
            characters: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gender */
            gender: string;
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Language Name */
            language_name: string;
            /** Seconds */
            seconds: number;
            /** Text */
            text: string;
            /** Voice */
            voice: string;
        };
        /** SpokenLanguage */
        SpokenLanguage: {
            /** English */
            english: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Quality
             * @enum {string}
             */
            quality: "good" | "fair" | "limited" | "unrated";
        };
        SseEvent: components["schemas"]["NodeEvent"] | components["schemas"]["TokenEvent"] | components["schemas"]["InterruptEvent"] | components["schemas"]["JobProgressEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
        /** TestOutcome */
        TestOutcome: {
            /**
             * Error
             * @default
             */
            error: string;
            /** Latency Ms */
            latency_ms: number;
            /** Ok */
            ok: boolean;
            /**
             * Sample
             * @default
             */
            sample: string;
        };
        /** TokenEvent */
        TokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "token";
            /** Node */
            node: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seq */
            seq: number;
            /** Text */
            text: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Ts */
            ts?: string;
        };
        /** TranscriptDetail */
        TranscriptDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Language Name */
            language_name: string;
            /** Preview */
            preview: string;
            /** Seconds */
            seconds: number;
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /**
             * Status
             * @enum {string}
             */
            status: "working" | "done" | "failed";
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** TranscriptPage */
        TranscriptPage: {
            /** Next Before */
            next_before: string | null;
            /** Transcripts */
            transcripts: components["schemas"]["TranscriptSummary"][];
        };
        /** TranscriptSummary */
        TranscriptSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Language Name */
            language_name: string;
            /** Preview */
            preview: string;
            /** Seconds */
            seconds: number;
            /**
             * Status
             * @enum {string}
             */
            status: "working" | "done" | "failed";
            /** Title */
            title: string;
        };
        /** UploadResult */
        UploadResult: {
            /** Bytes */
            bytes: number;
            /** Height */
            height: number;
            /** Key */
            key: string;
            /** Upload Id */
            upload_id: string;
            /** Width */
            width: number;
        };
        /** UsageDay */
        UsageDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Events */
            events: number;
            /** Kind */
            kind: string;
        };
        /** UsageReport */
        UsageReport: {
            /** Daily */
            daily: components["schemas"]["UsageDay"][];
            /** Days */
            days: number;
            /** Totals */
            totals: components["schemas"]["UsageTotal"][];
        };
        /** UsageTotal */
        UsageTotal: {
            /** Events */
            events: number;
            /** Kind */
            kind: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoPage */
        VideoPage: {
            /** Next Before */
            next_before: string | null;
            /** Videos */
            videos: components["schemas"]["VideoSummary"][];
        };
        /** VideoSummary */
        VideoSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Height */
            height?: number | null;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Poster Url */
            poster_url?: string | null;
            /** Prompt */
            prompt: string;
            /** Seconds */
            seconds: number;
            /**
             * Status
             * @enum {string}
             */
            status: "working" | "done" | "failed";
            /** Video Url */
            video_url?: string | null;
            /** Width */
            width?: number | null;
        };
        /** VoiceCatalog */
        VoiceCatalog: {
            /** Languages */
            languages: components["schemas"]["LanguageChoice"][];
        };
        /** VoiceChoice */
        VoiceChoice: {
            /** Default */
            default: boolean;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Quality */
            quality: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_log_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_admin_media_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaList"];
                };
            };
        };
    };
    set_media_admin_media__product_id___capability__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                capability: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaBindingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_media_admin_media__product_id___capability__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                capability: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_media_admin_media__product_id___capability__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                capability: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MediaBindingIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTestOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_admin_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
    set_model_admin_models__alias__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Binding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelUpdated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_model_admin_models__alias__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_admin_models__alias__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Binding"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_safeguards_admin_safeguards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafeguardsStatus"];
                };
            };
        };
    };
    set_safeguards_admin_safeguards_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafeguardsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafeguardsStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_songs_admin_songs_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSongPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_report_admin_usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_creations_creations_search_get: {
        parameters: {
            query: {
                q: string;
                kind?: ("song" | "image" | "video" | "speech" | "transcript" | "lipsync") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_images_products_wd_image_ai_images_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_products_wd_image_ai_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_products_wd_image_ai_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_products_wd_image_ai_images__image_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enhance_products_wd_image_ai_prompt_enhance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhanceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lipsyncs_products_wd_lipsync_ai_lipsyncs_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                status?: ("working" | "done" | "failed") | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LipSyncPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lipsync_products_wd_lipsync_ai_lipsyncs__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LipSyncSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lipsync_products_wd_lipsync_ai_lipsyncs__video_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_products_wd_lipsync_ai_lipsyncs__video_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enhance_products_wd_music_ai_prompt_enhance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhanceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_songs_products_wd_music_ai_songs_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_song_products_wd_music_ai_songs__song_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_products_wd_music_ai_songs__song_id__download__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
                kind: "audio" | "cover" | "video";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    languages_products_wd_stt_ai_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageCatalog"];
                };
            };
        };
    };
    list_transcripts_products_wd_stt_ai_transcripts_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                status?: ("working" | "done" | "failed") | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_products_wd_stt_ai_transcripts__transcript_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transcript_products_wd_stt_ai_transcripts__transcript_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_products_wd_stt_ai_transcripts__transcript_id__download_get: {
        parameters: {
            query?: {
                format?: "txt" | "srt" | "vtt" | "json";
            };
            header?: never;
            path: {
                transcript_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_speeches_products_wd_tts_ai_speeches_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeechPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_speech_products_wd_tts_ai_speeches__speech_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speech_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeechSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_speech_products_wd_tts_ai_speeches__speech_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speech_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_products_wd_tts_ai_speeches__speech_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speech_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_products_wd_tts_ai_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceCatalog"];
                };
            };
        };
    };
    enhance_products_wd_video_ai_prompt_enhance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhanceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_videos_products_wd_video_ai_videos_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                status?: ("working" | "done" | "failed") | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_products_wd_video_ai_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_products_wd_video_ai_videos__video_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_products_wd_video_ai_videos__video_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_products__product_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_products__product_id__uploads_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upload_products__product_id__uploads_images__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_media_products__product_id__uploads_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upload_products__product_id__uploads_media__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
