model_list:
  - model_name: default-chat
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: os.environ/OLLAMA_BASE_URL
  - model_name: lyrics-writer
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: os.environ/OLLAMA_BASE_URL
  - model_name: moderator
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: os.environ/OLLAMA_BASE_URL
